### ISSUE TITLE
What type of data storage does CSCS provide?

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/SKA#10]
Can different users use the same data storage? Is there already something implemented like this on CSCS.
This is useful for when massive files are interesting for different users.

**Comment by Lukas113** [comment]
As we've just discussed in the meeting, CSCS provides a shared data storage which is available to other CSCS users or to public users. According to Pablo this is possible for a few TB of data.

**Comment by Lukas113** [comment]
What we have to do is to figure out how this can be done.
