### ISSUE TITLE
Give the pipeline a new name

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/SKA#15]
- [ ] The pipeline should have good name, people can pronounce

**Comment by cvoegele** [comment]
Idea for the first 3 names, is if you put ska somwhere in it, but make it sound like a name, it should not interfere with the new rules by the ska to not use SKA for anything, but still make it sure to the users, that it is somehow connected.

😍 Adoska (Astronomical data (o=filler for pronunciation) ska) 
      - (filler letter could also be changed, eg: Adeska, Adaska = sounds a bit like alaska)
😍 Adoskap (Astronomical data (o=filler for pronunciation) ska pipeline)
😍 Podaska (Pipeline on data astronomical (a = filler) ska)
🤷🏻 Daska (Data astronomy ska)
🤷🏻 Padska (Pipeline astronomy data ska) → (harder to pronounce, as there are two consonants after each other)

These combine different functionality in the name, however I believe this is not the best idea, as the functionality might change and adapt drastically.

😒 SiCalmPIP Simulation, Calibration, imaging, pipeline
😭 pipsimage (pipeline, simulation, imaging) = sounds really boring

Some other ideas.:

😒 iPipeline4SKA (connected to the i4DS name)
💁 PuiPui (Sounds cute)

**Comment by deiruch** [comment]
I like **PuiPui** and **Pips** :)

@Lukas113, @rohitcbscient and @Stefan-Koegl What do you think? It'd be great to settle on a name for our first release next week.

**Comment by Stefan-Koegl** [comment]
**Pui Pui** Molcar (Japanese: PUI PUI モルカー, Hepburn: Pui Pui Morukā, "Pui Pui Cavy-Car") is a Japanese stop-motion short anime series
**PIPs** are Positive Impact Points - a ‘currency of change’ - that are earned and redeemed for verifiable daily life behaviors that benefit the planet, community and personal health.
I'm not really good with names, how about 
- SKA (or Swiss) Signal Processing Pipeline "S2P2" just to throw another idea in,. ... but it is a bit difficult to pronounce.   or 
- "DiT+" for Digital Torrent (and a plus always looks good :-) ) or
- "DITOR" for Digital Torrent
- ... or just "Karabo" it is a name from Southern Africa and means "answer" in Sotho and Tswana.

**Comment by cvoegele** [comment]
I feel like the existing meanings you mention @Stefan-Koegl  for PuiPui and PIPs are not problematic. PIPs might be more problematic because for python, pip is the package manager. When people start removing the s when talking, it might add some confusion @deiruch.

- S2P2 feels like a Star Wars robot. Maybe it could work. As our target audience are astronomers. Do they like Star Wars? But 
- Torrent in like a rapid stream of water is OK, but it might have a conflicting meaning with online piracy.

I like **Karabo**, easy to pronounce and a nice meaning, even though it is not really connected. Or PuiPui.

**Comment by rohitcbscient** [comment]
I am not good at names either, but it should be relatable and catchy at the same time. The good thing is that the letter "S" is common in words like Swiss, signal,  and SKA.
Here are some more suggestions:

SSKADS - Swiss SKA Data Simulator
S3P - Swiss SKA Signal Processor/Pipeline
SSKADP -  Swiss SKA Data Pipeline
DiTSS - Digital Twin for SKA Switzerland
What do you think? Karabo is fine with me too.

**Comment by deiruch** [comment]
Given the rather strict naming rules of the consortium indicates that we probably shouldn't use "SKA" in our project name. It might set us up for trouble.

Everybody appears to be happy with "Karabo". Perhaps we should append some other word, to make it Google-able. What about "Karabo Pipeline"?

**Comment by Stefan-Koegl** [comment]
OK for me.

**Comment by cvoegele** [comment]
I like this a lot. Perfect. Karabo Pipeline. I will be using this for now for the package names.
